export enum ChatTipo {
  INSTRUCTOR_DEPORTISTA = "INSTRUCTOR_DEPORTISTA",
  DEPORTISTA_INSTRUCTOR = "DEPORTISTA_INSTRUCTOR",
  INSTRUCTOR_ORGANIZACION = "INSTRUCTOR_ORGANIZACION",
  ORGANIZACION_INSTRUCTOR = "ORGANIZACION_INSTRUCTOR",
  EQUIPO = "EQUIPO"
}