export const appSettings={
    apiGeneral:"http://localhost:8080",
    apiLogin:"http://localhost:8080/auth/login/deportista",
    apiLoginOrg:"http://localhost:8080/auth/login/organizacion",
    apiLoginInst:"http://localhost:8080/auth/login/instructor",
    apiLoginAdmin:"http://localhost:8080/auth/login/admin",
    apiRutinas:"http://localhost:8080/rutinas",
    apiPosiciones:"http://localhost:8080/posiciones",
    apiEliminarRutinas:"http://localhost:8080/rutinas/eliminar",
    apiAgregarRutinas:"http://localhost:8080/rutinas/agregar",
    apiDeportistas:"http://localhost:8080/deportistas",
    apiRutinasJugador:"http://localhost:8080/rutinaJugador",
    apiVincularRutinas:"http://localhost:8080/rutinaJugador/vincular",
    apiEquipo:"http://localhost:8080/equipos",
    apiJugadorEquipo:"http://localhost:8080/equipos/jugadores",
    apiVincularEquipo:"http://localhost:8080/equipos/vincular",
    apiEliminarEquipos:"http://localhost:8080/equipos/eliminar",
    apiAgregarEquipos:"http://localhost:8080/equipos/agregar",
    apiRutinasInst:"http://localhost:8080/rutinas/total",
    apiEventoEquipo:"http://localhost:8080/eventosEquipo",
    apiEventoEquipos:"http://localhost:8080/eventosEquipo/equipos",
    apiVincularEvento:"http://localhost:8080/eventosEquipo/vincular",
    apiVideo:"http://localhost:8080/api/recursos/video",
    apiEjercicios:"http://localhost:8080/ejercicios",
    apiAgregarEjercicio:"http://localhost:8080/ejercicios/agregar",
    apiEliminarEjercicios:"http://localhost:8080/ejercicios/eliminar",
    apiDeportistaRutina: "http://localhost:8080/deportista",
    apiEventosFuturosDep: "http://localhost:8080/eventosFuturosDep",
    apiRutinasEjerciciosRecursos :"http://localhost:8080/rutinasdeportista",
    apiAgregarCheckin :"http://localhost:8080/checkin/agregar",
    apiEquipoDeportista: "http://localhost:8080/equiposDeportista",
    apicompletadas : "http://localhost:8080/checkin/completadas",
    apiincompletadas : "http://localhost:8080/checkin/incompletadas",
    apiAgregarEvento:"http://localhost:8080/organizacion/crear",
    apiListarEventosDeportista:"http://localhost:8080/eventosDeportista",
    apilistarFechasEvento:"http://localhost:8080/eventoFecha/listar",
    apiEliminarEventos:"http://localhost:8080/eliminarEvento",
    apiActualizarEvento: "http://localhost:8080/actualizarEvento",
    apiEventosFuturosOrg: "http://localhost:8080/eventosFuturosOrg",
    apiProximosEquipos: "http://localhost:8080/proximosEquipos",
    apiActualizarOrg: "http://localhost:8080/actualizarOrg",
    apiMetricasJugador: "http://localhost:8080/metricasJugador",
    apiAgregarMetrica: "http://localhost:8080/agregarMetrica",
    apiAgregarRecord: "http://localhost:8080/agregarRecord",
    apiRecordsJugador: "http://localhost:8080/recordsJugador",
    apiAgregarGoal: "http://localhost:8080/agregarGoal",
    apiGoalsJugador: "http://localhost:8080/goalsJugador",
    apiEvolucion: "http://localhost:8080/evolucion",
    apiCumplimiento: "http://localhost:8080/cumplimiento",
    apiProgresoObjetivos :"http://localhost:8080/progresoObjetivos",
    apiDesasociar:"http://localhost:8080/desasociar",
    apiEquiposEvento:"http://localhost:8080/eventosEquipo/listar",
    apiActualizarEquipo:"http://localhost:8080/equipos/editar",
    apiDeportes: "http://localhost:8080/deportes/list"

}